### ISSUE TITLE
[hsa-rocr] ‘const HsaNodeProperties’ has no member named ‘FamilyID’

### ISSUE THREAD

**Issue by nergdron** [rocm-arch/rocm-arch#924] opened 2022-12-06 17:09 UTC
```
[ 61%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/runtime.cpp.o
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/amd_cpu_agent.cpp: In member function ‘virtual hsa_status_t rocr::AMD::CpuAgent::GetInfo(hsa_agent_info_t, void*) const’:
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/amd_cpu_agent.cpp:371:63: error: ‘const HsaNodeProperties’ has no member named ‘FamilyID’
  371 |       *((uint32_t*)value) = static_cast<uint32_t>(properties_.FamilyID);
      |                                                               ^~~~~~~~
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/amd_aql_queue.cpp: In static member function ‘static bool rocr::AMD::AqlQueue::ExceptionHandler(hsa_signal_value_t, void*)’:
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/amd_aql_queue.cpp:1062:17: warning: comparison between ‘enum hsa_status_t’ and ‘enum<unnamed>’ [-Wenum-compare]
 1062 |   if (errorCode == HSA_STATUS_ERROR_MEMORY_FAULT) {
      |       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 62%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/signal.cpp.o
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/amd_gpu_agent.cpp: In member function ‘virtual hsa_status_t rocr::AMD::GpuAgent::GetInfo(hsa_agent_info_t, void*) const’:
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/amd_gpu_agent.cpp:1106:63: error: ‘const HsaNodeProperties’ has no member named ‘FamilyID’
 1106 |       *((uint32_t*)value) = static_cast<uint32_t>(properties_.FamilyID);
      |                                                               ^~~~~~~~
[ 63%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/queue.cpp.o
[ 64%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/cache.cpp.o
[ 65%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/svm_profiler.cpp.o
make[2]: *** [CMakeFiles/hsa-runtime64.dir/build.make:160: CMakeFiles/hsa-runtime64.dir/core/runtime/amd_cpu_agent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 66%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/common/shared.cpp.o
make[2]: *** [CMakeFiles/hsa-runtime64.dir/build.make:174: CMakeFiles/hsa-runtime64.dir/core/runtime/amd_gpu_agent.cpp.o] Error 1
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/runtime.cpp: In member function ‘hsa_status_t rocr::core::Runtime::PtrInfo(const void*, hsa_amd_pointer_info_t*, void* (*)(size_t), uint32_t*, hsa_agent_t**, PtrInfoBlockData*)’:
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/runtime.cpp:871:27: warning: ‘mappedNodes’ may be used uninitialized [-Wmaybe-uninitialized]
  871 |       assert(mappedNodes[i] <= max_node_id() &&
      |                           ^
/home/tessa/.cache/yay/hsa-rocr/src/ROCR-Runtime-rocm-5.4.0/src/core/runtime/runtime.cpp:766:13: note: ‘mappedNodes’ was declared here
  766 |   uint32_t* mappedNodes;
      |             ^~~~~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/hsa-runtime64.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hsa-rocr
```

**Comment by tpkessler** [comment] 2022-12-06 19:24
Duplicate of #920.

**Closed by tpkessler** 2022-12-06 19:24 UTC
Labels: build error
