### ISSUE TITLE
[rocsparse] compillation fails with: clang frontend command failed with exit code 70

### ISSUE THREAD

**Issue by jorge-barroso** [rocm-arch/rocm-arch#476] opened 2020-11-30 12:57 UTC
Everything works fine until the 53% shown below, then I get this stacktrace

```
[ 53%] Building CXX object library/CMakeFiles/rocsparse.dir/src/precond/rocsparse_csrilu0.cpp.o
fatal error: error in backend: Cannot select: 0x563cc50d4830: i64 = FrameIndex<0>
In function: _Z41csrgemm_fill_block_per_row_device_pointerI21rocsparse_complex_numIdELj128ELj16ELj256ELj137EEviPKiS3_PKT_S3_S3_S6_S3_S3_S6_S6_S3_S3_S6_S3_PiPS4_21rocsparse_index_base_S9_S9_S9_bb
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 12.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 59141509d659fd657965503bf29efb59e09d3253)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
[ 55%] Building CXX object library/CMakeFiles/rocsparse.dir/src/conversion/rocsparse_nnz.cpp.o
clang-12: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:368: library/CMakeFiles/rocsparse.dir/src/extra/rocsparse_csrgemm.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
fatal error: error in backend: Cannot select: 0x55bd77223568: i64 = FrameIndex<0>
In function: _Z30bsrilu0_general_device_pointerI21rocsparse_complex_numIdEdLj128ELj64ELb1EEv20rocsparse_direction_iPKiS4_PT_S4_iPiS4_S7_21rocsparse_index_base_iPKT0_PKS5_
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 12.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 59141509d659fd657965503bf29efb59e09d3253)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-12: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:394: library/CMakeFiles/rocsparse.dir/src/precond/rocsparse_bsrilu0.cpp.o] Error 70
fatal error: error in backend: Cannot select: 0x558bd181ccc8: i64 = FrameIndex<0>
In function: _Z31csrilu0_binsearch_device_kernelI21rocsparse_complex_numIdEdLj256ELj64ELb1EEviPKiS3_PT_S3_PiS3_S6_21rocsparse_index_base_iPKT0_PKS4_
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 12.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 59141509d659fd657965503bf29efb59e09d3253)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-12: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:420: library/CMakeFiles/rocsparse.dir/src/precond/rocsparse_csrilu0.cpp.o] Error 70
```

**Comment by acxz** [comment] 2020-11-30 13:22
I was able to build the package successfully, just now.

`rocsparse` binary is available on arch4edu so you can install it from there for now, if you can't build it. We only recommend people building the packages if they are developing/contributing to this repo.

I'll leave this issue open for a week to see if others experience the issue, and if not I'll go ahead and close it.
Feel free to close it on your own if you get the `arch4edu` binary working.

**Comment by tpkessler** [comment] 2020-11-30 13:25
I cannot reproduce this. Which version of `llvm-amdgpu` are you using? The git version of the package is known to not always work.

**Comment by jorge-barroso** [comment] 2020-11-30 13:27
I've done a quick pacman -Qs llvm and these are my related packages, hope it helps bring some light

![image](https://user-images.githubusercontent.com/8150057/100615648-2e108b80-3318-11eb-953c-a0afc6950d41.png)

**Comment by acxz** [comment] 2020-11-30 13:43
For future reference can you post text instead of images. It makes it easier for people to search through with search engines or githubs search feature.

**Comment by jorge-barroso** [comment] 2020-11-30 13:49
> For future reference please post text instead of images. It makes it easier for people to search through with search engines or githubs search feature. (This is generally true for anytime you post a bug report elsewhere as well)

True good point, I've updated my comment

**Comment by acxz** [comment] 2020-12-02 02:13
@jorge-barroso were you able to try the arch4edu binaries?

**Comment by jorge-barroso** [comment] 2020-12-02 02:14
> @jorge-barroso were you able to try the arch4edu binaries?

Yes I tried with arch4edu with no issues

**Closed** 2020-12-02 13:09 UTC

**Comment by trougnouf** [comment] 2022-01-02 15:11
I'm getting the same issue:

```bash
[ 74%] Building CXX object library/CMakeFiles/rocsparse.dir/src/precond/rocsparse_gtsv_no_pivot.cpp.o
fatal error: error in backend: Cannot select: 0x55f408c9b258: i64 = FrameIndex<0>
In function: _Z15bsrilu0_generalILj128ELj64ELb1E21rocsparse_complex_numIdEPKdPKS1_Ev20rocsparse_direction_iPKiS8_PT2_S8_iPiS8_SB_21rocsparse_index_base_iT3_T4_
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://aur.archlinux.org/rocm-llvm 2535dd87f3cdec8327146099f946de998173c412)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
fatal error: error in backend: Cannot select: 0x565097013940: i64 = FrameIndex<0>
In function: _Z17csrilu0_binsearchILj256ELj64ELb1E21rocsparse_complex_numIdEPKdPKS1_EviPKiS7_PT2_S7_PiS7_SA_21rocsparse_index_base_iT3_T4_
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://aur.archlinux.org/rocm-llvm 2535dd87f3cdec8327146099f946de998173c412)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-13: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:1350: library/CMakeFiles/rocsparse.dir/src/precond/rocsparse_bsrilu0.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
clang-13: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:1378: library/CMakeFiles/rocsparse.dir/src/precond/rocsparse_csrilu0.cpp.o] Error 70
fatal error: error in backend: Cannot select: 0x557c1dfbe7e0: i64 = FrameIndex<0>
In function: _Z41csrgemm_fill_block_per_row_device_pointerILj128ELj16ELj256ELj137Eii21rocsparse_complex_numIdEEvT4_PKS2_S4_PKT5_PKT3_S4_S7_SA_S4_S7_S7_SA_S4_S7_SA_PS2_PS5_21rocsparse_index_base_SD_SD_SD_bb
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://aur.archlinux.org/rocm-llvm 2535dd87f3cdec8327146099f946de998173c412)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-13: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:1294: library/CMakeFiles/rocsparse.dir/src/extra/rocsparse_csrgemm.cpp.o] Error 70
```
