### ISSUE TITLE
[comgr] Packages fail to build 

### ISSUE THREAD

**Issue by disobeyedtoast** [rocm-arch/rocm-arch#443] opened 2020-09-26 19:46 UTC
At a certain point I get the following compiler error:

```
/home/crunch/.cache/yay/comgr/src/ROCm-CompilerSupport-rocm-3.8.0/lib/comgr/src/comgr-metadata.cpp:587:13: error: ‘EF_AMDGPU_MACH_AMDGCN_GFX1030’ is not a member of ‘llvm::ELF’; did you mean ‘EF_AMDGPU_MACH_AMDGCN_GFX1010’?
  587 |   case ELF::EF_AMDGPU_MACH_AMDGCN_GFX1030:
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             EF_AMDGPU_MACH_AMDGCN_GFX1010
make[2]: *** [CMakeFiles/amd_comgr.dir/build.make:147: CMakeFiles/amd_comgr.dir/src/comgr-metadata.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/crunch/.cache/yay/comgr/src/build'
make[1]: *** [CMakeFiles/Makefile2:762: CMakeFiles/amd_comgr.dir/all] Error 2
make[1]: Leaving directory '/home/crunch/.cache/yay/comgr/src/build'
make: *** [Makefile:182: all] Error 2
make: Leaving directory '/home/crunch/.cache/yay/comgr/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
```

I apologize if I have left out any crucial information, I do not know much about debugging compilers.

**Comment by disobeyedtoast** [comment] 2020-09-27 11:17
My GCC is at 10.2.0 and I am on Manjaro. What would the other dependencies for this package be so I can report what version they are here?

**Comment by acxz** [comment] 2020-09-27 12:45
You can check what dependencies a package has by looking at the `depends` and `makedepends` field of the PKGBUILD. However, do note that we do not officially support Manjaro. Basically if we can't reproduce your issue then we can't fix it. We  instead recommend Arch repo compatible distributions, such as [EndeavourOS](https://endeavouros.com/) if you are looking for a GUI based install. Note with EndeavourOS you would be able to use [arch4edu](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux) which is a binary repo, so you don't have to compile any of these packages.

**Comment by acxz** [comment] 2020-10-06 16:23
Going ahead and closing this as this is a Manjaro issue that no one has been able to reproduce.

**Closed by acxz** 2020-10-06 16:23 UTC
