### ISSUE TITLE
[hip-runtime-amd, hsa-rocr, rocminfo] Build errors while trying to update to 5.3.0-1

### ISSUE THREAD

**Issue by AmyRoxwell** [rocm-arch/rocm-arch#873] opened 2022-10-09 19:25 UTC
While trying to update I get the following errors:
hsa-rocr:
```
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Error 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hsa-rocr
```
rocminfo:
```
/home/amyroxwell/.cache/yay/rocminfo/src/rocminfo-rocm-5.3.0/rocminfo.cc:58:10: fatal error: hsa/hsa.h: No such file or directory
   58 | #include "hsa/hsa.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rocminfo.dir/build.make:79: CMakeFiles/rocminfo.dir/rocminfo.cc.o] Error 1
make[2]: Leaving directory '/home/amyroxwell/.cache/yay/rocminfo/src/build'
make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/rocminfo.dir/all] Error 2
make[1]: Leaving directory '/home/amyroxwell/.cache/yay/rocminfo/src/build'
make: *** [Makefile:159: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: rocminfo
```
hip-runtime-amd
```
CMake Error at /home/amyroxwell/.cache/yay/hip-runtime-amd/src/ROCclr-rocm-5.3.0/cmake/ROCclrHSA.cmake:21 (find_package):
  Could not find a configuration file for package "hsa-runtime64" that is
  compatible with requested version "1.6".

  The following configuration files were considered but not accepted:

    /opt/rocm/lib/cmake/hsa-runtime64/hsa-runtime64-config.cmake, version: 1.5.0

Call Stack (most recent call first):
  /home/amyroxwell/.cache/yay/hip-runtime-amd/src/ROCclr-rocm-5.3.0/cmake/ROCclr.cmake:132 (include)
  src/cmake/FindROCclr.cmake:51 (include)
  src/CMakeLists.txt:57 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/amyroxwell/.cache/yay/hip-runtime-amd/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hip-runtime-amd
 ```
Logs:
hsa-rocr: [CMakeOutput.log](https://github.com/rocm-arch/rocm-arch/files/9742403/CMakeOutput.log)
rocminf: [CMakeOutput.log](https://github.com/rocm-arch/rocm-arch/files/9742402/CMakeOutput.log)
hip-runtime-amd: [CMakeOutput.log](https://github.com/rocm-arch/rocm-arch/files/9742392/CMakeOutput.log)

Edit: I forgot to say that I'm using EndeavourOS

**Comment by BishopWolf** [comment] 2022-10-09 19:48
I have this same error

```
:: 6 Packages to upgrade.
6  aur/hip-runtime-amd  5.2.3-2 -> 5.3.0-1
5  aur/hipcub           5.2.3-1 -> 5.3.0-1
4  aur/hsa-rocr         5.2.3-2 -> 5.3.0-1
3  aur/rocminfo         5.2.3-2 -> 5.3.0-1
2  aur/rocprim          5.2.3-2 -> 5.3.0-1
1  aur/rocrand          5.2.3-2 -> 5.3.0-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
```

then

```
[  4%] BUILDING bitcode for kCodeTrapHandlerV2_11...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

and
```
[ 30%] BUILDING bitcode for ocl_blit_object_gfx1036...
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Using Arch

**Comment by mluckau** [comment] 2022-10-09 21:53
I have the same error, I using Manjaro.

`[  2%] BUILDING bitcode for kCodeTrapHandlerV2_1010...
[  2%] BUILDING bitcode for kCodeTrapHandlerV2_9...
[  2%] BUILDING bitcode for ocl_blit_object_gfx700...
[  3%] BUILDING bitcode for ocl_blit_object_gfx701...
[  5%] BUILDING bitcode for kCodeTrapHandlerV2_11...
[  5%] BUILDING bitcode for kCodeTrapHandlerV2_10...
[  6%] BUILDING bitcode for ocl_blit_object_gfx801...
[  7%] BUILDING bitcode for ocl_blit_object_gfx803...
[  8%] BUILDING bitcode for ocl_blit_object_gfx802...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx810...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx805...
[ 11%] BUILDING bitcode for ocl_blit_object_gfx900...
[ 12%] BUILDING bitcode for ocl_blit_object_gfx902...
[ 13%] BUILDING bitcode for ocl_blit_object_gfx904...
[ 14%] Built target link_libhsa-runtime64.so.1
[ 14%] Built target link_libhsa-runtime64.so
[ 14%] BUILDING bitcode for ocl_blit_object_gfx702...
[ 16%] BUILDING bitcode for ocl_blit_object_gfx908...
[ 16%] BUILDING bitcode for ocl_blit_object_gfx906...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[ 17%] BUILDING bitcode for ocl_blit_object_gfx909...
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[ 18%] BUILDING bitcode for ocl_blit_object_gfx90a...
[ 20%] BUILDING bitcode for ocl_blit_object_gfx1010...
[ 20%] BUILDING bitcode for ocl_blit_object_gfx90c...
[ 21%] BUILDING bitcode for ocl_blit_object_gfx1012...
[ 22%] BUILDING bitcode for ocl_blit_object_gfx1011...
[ 23%] BUILDING bitcode for ocl_blit_object_gfx1013...
[ 25%] BUILDING bitcode for ocl_blit_object_gfx1031...
[ 25%] BUILDING bitcode for ocl_blit_object_gfx1030...
[ 26%] BUILDING bitcode for ocl_blit_object_gfx1032...
[ 27%] BUILDING bitcode for ocl_blit_object_gfx1033...
[ 28%] BUILDING bitcode for ocl_blit_object_gfx1034...
[ 29%] BUILDING bitcode for ocl_blit_object_gfx1035...
[ 30%] BUILDING bitcode for ocl_blit_object_gfx1036...
[ 31%] BUILDING bitcode for ocl_blit_object_gfx1100...
[ 32%] BUILDING bitcode for ocl_blit_object_gfx1102...
[ 33%] BUILDING bitcode for ocl_blit_object_gfx1103...
clang-14: error: invalid target ID 'gfx1103'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1102'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:173: image/blit_src/ocl_blit_object_gfx1103] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:168: image/blit_src/ocl_blit_object_gfx1102] Fehler 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Fehler 1
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:163: image/blit_src/ocl_blit_object_gfx1100] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
 -> Fehler beim Erstellen: hsa-rocr
`

**Comment by rubentest** [comment] 2022-10-09 23:55
The same on manjaro but at 1103

```
[ 30%] BUILDING bitcode for ocl_blit_object_gfx1036...
[ 31%] BUILDING bitcode for ocl_blit_object_gfx1100...
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Error 1
make[2]: *** Se espera a que terminen otras tareas....
[ 32%] BUILDING bitcode for ocl_blit_object_gfx1102...
[ 33%] BUILDING bitcode for ocl_blit_object_gfx1103...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:163: image/blit_src/ocl_blit_object_gfx1100] Error 1
clang-14: error: invalid target ID 'gfx1102'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:168: image/blit_src/ocl_blit_object_gfx1102] Error 1
clang-14: error: invalid target ID 'gfx1103'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:173: image/blit_src/ocl_blit_object_gfx1103] Error 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by tpkessler** [comment] 2022-10-10 09:57
Duplicate of #870

**Closed by tpkessler** 2022-10-10 09:57 UTC
