### ISSUE TITLE
[hsa-rocr] Build failure

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#876] opened 2022-10-11 18:16 UTC
I'm getting failures as follows:

```
==> Starting build()...
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Found LibElf: /usr/lib/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Checking for module 'libdrm'
--   Found libdrm, version 2.4.113
-- Looking for __NR_memfd_create
-- Looking for __NR_memfd_create - found
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/libtinfo.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.12") 
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.10.2") 
Using CPACK_DEBIAN_PACKAGE_RELEASE local
RESULT_VARIABLE No such file or directory OUTPUT_VARIABLE: 
CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- Configuring done
-- Generating done
-- Build files have been written to: /home/koz/.cache/paru/clone/hsa-rocr/src/build
[  1%] BUILDING bitcode for kCodeTrapHandlerV2_10...
[  2%] BUILDING bitcode for kCodeTrapHandlerV2_9...
[  4%] BUILDING bitcode for ocl_blit_object_gfx801...
[  4%] BUILDING bitcode for kCodeTrapHandlerV2_1010...
[  5%] BUILDING bitcode for ocl_blit_object_gfx702...
[  6%] BUILDING bitcode for ocl_blit_object_gfx802...
[  8%] BUILDING bitcode for ocl_blit_object_gfx701...
[  8%] BUILDING bitcode for ocl_blit_object_gfx803...
[ 10%] BUILDING bitcode for kCodeTrapHandlerV2_11...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx900...
[ 11%] BUILDING bitcode for ocl_blit_object_gfx700...
[ 11%] BUILDING bitcode for ocl_blit_object_gfx810...
[ 12%] BUILDING bitcode for ocl_blit_object_gfx805...
[ 14%] BUILDING bitcode for ocl_blit_object_gfx906...
[ 14%] BUILDING bitcode for ocl_blit_object_gfx902...
[ 15%] BUILDING bitcode for ocl_blit_object_gfx904...
[ 18%] BUILDING bitcode for ocl_blit_object_gfx90a...
[ 18%] BUILDING bitcode for ocl_blit_object_gfx909...
[ 19%] BUILDING bitcode for ocl_blit_object_gfx90c...
[ 19%] BUILDING bitcode for ocl_blit_object_gfx908...
[ 20%] BUILDING bitcode for ocl_blit_object_gfx1010...
[ 20%] Built target link_libhsa-runtime64.so.1
[ 20%] Built target link_libhsa-runtime64.so
[ 22%] BUILDING bitcode for ocl_blit_object_gfx1011...
[ 22%] BUILDING bitcode for ocl_blit_object_gfx1012...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 23%] BUILDING bitcode for ocl_blit_object_gfx1013...
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: clang-14error: : ld.lld command failed with exit code 1 (use -v to see invocation)error: 
unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:117: core/runtime/trap_handler/kCodeTrapHandlerV2_9.hsaco] Error 1
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:102: core/runtime/trap_handler/kCodeTrapHandlerV2_10.hsaco] Error 1
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:107: core/runtime/trap_handler/kCodeTrapHandlerV2_1010.hsaco] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] BUILDING bitcode for ocl_blit_object_gfx1031...
[ 25%] BUILDING bitcode for ocl_blit_object_gfx1030...
[ 26%] BUILDING bitcode for ocl_blit_object_gfx1032...
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:243: image/blit_src/ocl_blit_object_gfx909] Error 1
make[2]: *** Waiting for unfinished jobs....
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:238: image/blit_src/ocl_blit_object_gfx908] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:208: image/blit_src/ocl_blit_object_gfx805] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:118: image/blit_src/ocl_blit_object_gfx1012] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:193: image/blit_src/ocl_blit_object_gfx801] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:108: image/blit_src/ocl_blit_object_gfx1010] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:183: image/blit_src/ocl_blit_object_gfx701] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:218: image/blit_src/ocl_blit_object_gfx900] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:228: image/blit_src/ocl_blit_object_gfx904] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:113: image/blit_src/ocl_blit_object_gfx1011] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:233: image/blit_src/ocl_blit_object_gfx906] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:253: image/blit_src/ocl_blit_object_gfx90c] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:188: image/blit_src/ocl_blit_object_gfx702] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:223: image/blit_src/ocl_blit_object_gfx902] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:178: image/blit_src/ocl_blit_object_gfx700] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:203: image/blit_src/ocl_blit_object_gfx803] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:248: image/blit_src/ocl_blit_object_gfx90a] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:198: image/blit_src/ocl_blit_object_gfx802] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:213: image/blit_src/ocl_blit_object_gfx810] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:123: image/blit_src/ocl_blit_object_gfx1013] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:128: image/blit_src/ocl_blit_object_gfx1030] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:133: image/blit_src/ocl_blit_object_gfx1031] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:138: image/blit_src/ocl_blit_object_gfx1032] Error 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
```

Specifically:

```
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
```

**Comment by fabiscafe** [comment] 2022-10-11 20:57
This is a duplicate of #870

**Comment by BishopWolf** [comment] 2022-10-11 22:27
870 was closed with false solution. build in clean chroot is no solution at all! hsa-rocr is the only on package that does not uses rocm-cmake and is using system cmake. Please fix this

**Comment by tpkessler** [comment] 2022-10-12 11:40
> build in clean chroot is no solution at all

It is the only solution. All arch packages are built in a clean chroot.

>rocm-cmake and is using system cmake

rocm-cmake is a collection of cmake files, not an alternative implementation of cmake, see `pacman -Ql rocm-cmake`.

> build anything you see this

hsa-rocr does not need clang from rocm-llvm to build

**Comment by tpkessler** [comment] 2022-10-14 16:12
Closing this as duplicate of #870

**Closed by tpkessler** 2022-10-14 16:12 UTC
