### ISSUE TITLE
[hip-nvcc] does not build in clean chroot

### ISSUE THREAD

**Issue by lahwaacz** [rocm-arch/rocm-arch#263] opened 2020-06-19 08:26 UTC
Build log (attempting to build [hip-nvcc](https://aur.archlinux.org/packages/hip-nvcc/) in a clean chroot):
```
==> Starting build()...
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIP Platform: nvcc
-- HIP Compiler: hcc
-- HIP will be installed in: /opt/rocm/hip
-- ROCM Installation path(ROCM_PATH): /opt/rocm
--
HSA runtime in:
CMake Deprecation Warning at CMakeLists.txt:601 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Testing targets will not be available. To enable them please ensure that the HIP installation directory is writeable. Use -DCMAKE_INSTALL_PREFIX to specify a suitable location
-- Configuring done
-- Generating done
-- Build files have been written to: /build/hip-nvcc/src/build
==> Entering fakeroot environment...
==> Starting package()...
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "/build/hip-nvcc/src/build/.hipInfo": No such file
  or directory.


make: *** [Makefile:94: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by acxz** [comment] 2020-06-21 00:32
Yep I can reproduce the problem seems like it's trying to install `.hipInfo` even tho its not built.

**Comment by acxz** [comment] 2020-06-21 00:39
I went ahead and patched it, if you could try installing the latest version `3.5.1` from the AUR that would be great.
Labelling this issue as patched and leaving it open until the patch is not necessary.

**Comment by lahwaacz** [comment] 2020-06-21 10:32
@acxz Thanks, now the build succeeds.

**Comment by acxz** [comment] 2020-06-21 14:12
Glad to hear it works

> leaving it open until the patch is not necessary.

Reopening

**Comment by lahwaacz** [comment] 2020-06-21 14:27
> Glad to hear it works

Well, not exactly... #266

**Comment by acxz** [comment] 2020-06-23 00:52
Ah updated the patch for this package, also upstream PR here: https://github.com/ROCm-Developer-Tools/HIP/pull/2113

**Comment by tpkessler** [comment] 2021-05-15 12:29
This issue seems to be fully resolved with newer ROCm versions. Please reopen it @lahwaacz if your problem persists.

**Closed by tpkessler** 2021-05-15 12:29 UTC
Labels: build error, patched
