### ISSUE TITLE
[rocm-llvm-mlir] mlir/Dialect/Func/IR/FuncOps.h.inc: No such file or directory

### ISSUE THREAD

**Issue by expenses** [rocm-arch/rocm-arch#837] opened 2022-07-31 13:53 UTC
Hi, I'm getting this error when trying to build `rocm-llvm-mlir`:
```
In file included from /home/ashley/rocm-arch/rocm-llvm-mlir/src/llvm-project-mlir-rocm-5.3.0/mlir/include/mlir/Dialect/MIGraphX/PassDetail.h:12,
                 from /home/ashley/rocm-arch/rocm-llvm-mlir/src/llvm-project-mlir-rocm-5.3.0/mlir/lib/Dialect/MIGraphX/MiGraphXTransform.cpp:17:
/home/ashley/rocm-arch/rocm-llvm-mlir/src/llvm-project-mlir-rocm-5.3.0/external/llvm-project/mlir/include/mlir/Dialect/Func/IR/FuncOps.h:29:10: fatal error: mlir/Dialect/Func/IR/FuncOps.h.inc: No such file or directory
   29 | #include "mlir/Dialect/Func/IR/FuncOps.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Happens both with the PKGBUILD on the AUR and in this repo, with and without the patch in https://github.com/rocm-arch/rocm-arch/issues/818 applied.

Kernel: 5.18.14-arch1-1
`AMDGPU_TARGETS` environment variable: `gfx1030` (didn't seem to make a difference though)

**Comment by tpkessler** [comment] 2022-07-31 14:00
Hi @expenses! What is the content of your `/etc/makepkg.conf`? In #787 we had a similar issue caused by a single-thread build of the package.

**Comment by expenses** [comment] 2022-07-31 18:15
I believe that `/etc/makepkg.conf` is just the defaults. Here's is the contents with comments stripped:

```

DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
          'ftp::/usr/bin/curl -qgfC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
          'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'rsync::/usr/bin/rsync --no-motd -z %u %o'
          'scp::/usr/bin/scp -C %u %o')


VCSCLIENTS=('bzr::bzr'
            'fossil::fossil'
            'git::git'
            'hg::mercurial'
            'svn::subversion')

CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="$DEBUG_CFLAGS"

BUILDENV=(!distcc color !ccache check !sign)

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug !lto)

INTEGRITY_CHECK=(sha256)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"
MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
DBGSRCDIR="/usr/src/debug"


COMPRESSGZ=(gzip -c -f -n)
COMPRESSBZ2=(bzip2 -c -f)
COMPRESSXZ=(xz -c -z -)
COMPRESSZST=(zstd -c -z -q -)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZO=(lzop -q)
COMPRESSZ=(compress -c -f)
COMPRESSLZ4=(lz4 -q)
COMPRESSLZ=(lzip -c -f)

PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'
```

I've attached the full thing as a .zip:

[makepkg.conf.zip](https://github.com/rocm-arch/rocm-arch/files/9229419/makepkg.conf.zip)

I also have some environment variables set in `config.fish`:
```
set -x MOZ_ENABLE_WAYLAND 1
set -x CMAKE_BUILD_PARALLEL_LEVEL 8
set -x VK_ICD_FILENAMES /usr/share/vulkan/icd.d/intel_icd.i686.json:/usr/share/vulk
an/icd.d/intel_icd.x86_64.json
set -x RUST_LOG info
set -x NINJAFLAGS "-j8"
set -x AMDGPU_TARGETS gfx1030
```

I tried unsetting `CMAKE_BUILD_PARALLEL_LEVEL`, `AMDGPU_TARGETS` and `NINJAFLAGS` but I got the same error.

**Comment by acxz** [comment] 2022-08-02 01:43
You should be able to add `MAKEFLAGS="-j2"` or `MAKEFLAGS="-j4"` to add parallelization and that should move you along the compilation process.

**Comment by acxz** [comment] 2022-08-09 23:24
Closing as dup of #787

**Closed by acxz** 2022-08-09 23:24 UTC
Labels: build error
