### ISSUE TITLE
[hsa-rocr]   ERROR: A failure occurred in build()

### ISSUE THREAD

**Issue by grinness** [rocm-arch/rocm-arch#884] opened 2022-10-16 16:35 UTC
Hi,

trying to build rocm5.3, following usual instructions, clean build:
```
export NINJAFLAGS="-j24"
export AMDGPU_TARGETS="gfx1030"  
yay -S rocm-hip-sdk rocm-opencl-sdk
```

the first 4 packages build fine (rocm-llvm, rocm-core, rocm-cmake, rocm-device-libs) however hsa-rocr breaks:

```
Using CPACK_DEBIAN_PACKAGE_RELEASE local
RESULT_VARIABLE No such file or directory OUTPUT_VARIABLE: 
CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marco/.cache/yay/hsa-rocr/src/build
[  1%] BUILDING bitcode for ocl_blit_object_gfx700...
[  1%] BUILDING bitcode for ocl_blit_object_gfx803...
[  3%] BUILDING bitcode for ocl_blit_object_gfx701...
[  4%] BUILDING bitcode for ocl_blit_object_gfx900...
[  4%] BUILDING bitcode for kCodeTrapHandlerV2_1010...
[  5%] BUILDING bitcode for ocl_blit_object_gfx801...
[  7%] BUILDING bitcode for ocl_blit_object_gfx702...
[  7%] BUILDING bitcode for kCodeTrapHandlerV2_9...
[  8%] BUILDING bitcode for ocl_blit_object_gfx810...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx802...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx805...
[ 12%] BUILDING bitcode for ocl_blit_object_gfx908...
[ 13%] BUILDING bitcode for kCodeTrapHandlerV2_11...
[ 13%] BUILDING bitcode for kCodeTrapHandlerV2_10...
[ 14%] BUILDING bitcode for ocl_blit_object_gfx902...
[ 15%] BUILDING bitcode for ocl_blit_object_gfx904...
[ 16%] BUILDING bitcode for ocl_blit_object_gfx906...
[ 18%] BUILDING bitcode for ocl_blit_object_gfx909...
[ 18%] BUILDING bitcode for ocl_blit_object_gfx90a...
[ 19%] BUILDING bitcode for ocl_blit_object_gfx1010...
[ 20%] BUILDING bitcode for ocl_blit_object_gfx1011...
[ 21%] BUILDING bitcode for ocl_blit_object_gfx90c...
[ 21%] Built target link_libhsa-runtime64.so.1
[ 21%] Built target link_libhsa-runtime64.so
[ 23%] BUILDING bitcode for ocl_blit_object_gfx1012...
[ 23%] BUILDING bitcode for ocl_blit_object_gfx1013...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 24%] BUILDING bitcode for ocl_blit_object_gfx1030...
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:102: core/runtime/trap_handler/kCodeTrapHandlerV2_10.hsaco] Error 1
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:107: core/runtime/trap_handler/kCodeTrapHandlerV2_1010.hsaco] Error 1
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:117: core/runtime/trap_handler/kCodeTrapHandlerV2_9.hsaco] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] BUILDING bitcode for ocl_blit_object_gfx1031...
[ 26%] BUILDING bitcode for ocl_blit_object_gfx1033...
[ 27%] BUILDING bitcode for ocl_blit_object_gfx1032...
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:183: image/blit_src/ocl_blit_object_gfx701] Error 1
make[2]: *** Waiting for unfinished jobs....
error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:253: image/blit_src/ocl_blit_object_gfx90c] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:228: image/blit_src/ocl_blit_object_gfx904] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:243: image/blit_src/ocl_blit_object_gfx909] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:128: image/blit_src/ocl_blit_object_gfx1030] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:123: image/blit_src/ocl_blit_object_gfx1013] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:218: image/blit_src/ocl_blit_object_gfx900] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:193: image/blit_src/ocl_blit_object_gfx801] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:188: image/blit_src/ocl_blit_object_gfx702] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:118: image/blit_src/ocl_blit_object_gfx1012] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:203: image/blit_src/ocl_blit_object_gfx803] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:213: image/blit_src/ocl_blit_object_gfx810] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:108: image/blit_src/ocl_blit_object_gfx1010] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:208: image/blit_src/ocl_blit_object_gfx805] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:233: image/blit_src/ocl_blit_object_gfx906] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:113: image/blit_src/ocl_blit_object_gfx1011] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:223: image/blit_src/ocl_blit_object_gfx902] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:238: image/blit_src/ocl_blit_object_gfx908] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:178: image/blit_src/ocl_blit_object_gfx700] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:248: image/blit_src/ocl_blit_object_gfx90a] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:198: image/blit_src/ocl_blit_object_gfx802] Error 1
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:138: image/blit_src/ocl_blit_object_gfx1032] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:133: image/blit_src/ocl_blit_object_gfx1031] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:143: image/blit_src/ocl_blit_object_gfx1033] Error 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hsa-rocr
```

**Comment by lahwaacz** [comment] 2022-10-16 18:37
Duplicate of #870, search the closed issues.

The README talks about a _clean chroot_, not _clean build_.

**Comment by grinness** [comment] 2022-10-16 20:06
there are no packages installed on my system from rocm-arch repo.
when I run yay -S  I also force clean build to get rid of old cached stuff.
It is exactly the same as 'clean root'

**Comment by lahwaacz** [comment] 2022-10-16 20:19
No, it is not. Only dependencies of the package being built get installed in the chroot, but you have other packages installed. In your case, the problem is the `clang` package.

**Comment by grinness** [comment] 2022-10-16 20:42
Well, the problem is that the package in question should know better than picking up the wrong clang
Is there a cmake flag to indicate to use the one coming with rocm (I assume rocm-llvm, which should be in /opt/rocm)

**Comment by grinness** [comment] 2022-10-16 21:51
Here it is, there is no need of 'clean chroot', just set correctly the environment variables (4 exports in total) in the PKGBUILD, below the build() function:

```
build() {
  export CXX=/opt/rocm/llvm/bin/clang++
  export CC=/opt/rocm/llvm/bin/clang
  export Clang_DIR=/opt/rocm/llvm/lib/cmake/clang
  export LLVM_DIR=/opt/rocm/llvm/lib/cmake/llvm
  cmake \
    -Wno-dev \
    -B build \
    -S "$_dirname/src" \
    -DCMAKE_INSTALL_PREFIX=/opt/rocm \
    -DCMAKE_CXX_FLAGS='-DNDEBUG' \

  cmake --build build
}

```

**Comment by grinness** [comment] 2022-10-16 21:53
Below the full PKGBUILD -- again no need of 'clean chroot':
```
# Maintainer: Torsten Keßler <t dot kessler at posteo dot de>
# Contributor: acxz <akashpatel2008 at yahoo dot com>
# Contributor: Olaf Leidinger <oleid@mescharet.de>
# Contributor: Bruno Filipe <bmilreu@gmail.com>
# Contributor: Jakub Okoński <jakub@okonski.org>
# Contributor: Ranieri Althoff <ranisalt+aur at gmail.com>

pkgname=hsa-rocr
pkgver=5.3.0
pkgrel=1
pkgdesc='HSA Runtime API and runtime for ROCm'
arch=('x86_64')
url='https://rocmdocs.amd.com/en/latest/Installation_Guide/ROCR-Runtime.html'
license=('custom:NCSAOSL')
depends=('libelf' 'hsakmt-roct' 'rocm-device-libs')
makedepends=('cmake' 'rocm-llvm' 'xxd')
_git='https://github.com/RadeonOpenCompute/ROCR-Runtime'
source=("${pkgname}-${pkgver}.tar.gz::$_git/archive/rocm-$pkgver.tar.gz")
sha256sums=('b51dbedbe73390e0be748b92158839c82d7fa0e514fede60aa7696dc498facf0')
_dirname="$(basename "$_git")-$(basename "${source[0]}" .tar.gz)"

build() {
  export CXX=/opt/rocm/llvm/bin/clang++
  export CC=/opt/rocm/llvm/bin/clang
  export Clang_DIR=/opt/rocm/llvm/lib/cmake/clang
  export LLVM_DIR=/opt/rocm/llvm/lib/cmake/llvm
  cmake \
    -Wno-dev \
    -B build \
    -S "$_dirname/src" \
    -DCMAKE_INSTALL_PREFIX=/opt/rocm \
    -DCMAKE_CXX_FLAGS='-DNDEBUG' \

  cmake --build build
}

package() {
  DESTDIR="$pkgdir" cmake --install build

  install -Dm644 "$_dirname/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  echo "/opt/rocm/hsa/lib" > "$pkgname.conf"
  install -Dm644 "$pkgname.conf" "$pkgdir/etc/ld.so.conf.d/$pkgname.conf"
}


```

**Comment by grinness** [comment] 2022-10-16 23:57
see PR:
https://github.com/rocm-arch/rocm-arch/pull/885

**Comment by tpkessler** [comment] 2022-10-17 06:30
Duplicate of #870. See the readme for details.

**Closed by tpkessler** 2022-10-17 06:30 UTC

**Comment by grinness** [comment] 2022-10-17 08:37
The issue is still open. ...

**Comment by tpkessler** [comment] 2022-10-17 12:10
You can:

* build the package in a clean chroot with
   - paru --chroot
   - or according to [the wiki](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)
 * include arch4edu and obtain a binary copy of `hsa-rocr`(built in a clean chroot for you on a server)
 * or download the binary from arch4edu's [github page](https://github.com/arch4edu/cactus/actions/runs/3214841000)
 * call `env` with the parameters given in the readme.

Four solutions for one issue.
