### ISSUE TITLE
[hsa-rocr] invalid target ID 'gfx1100'

### ISSUE THREAD

**Issue by nidjan** [rocm-arch/rocm-arch#893] opened 2022-10-19 09:56 UTC
```
[  7%] Built target link_libhsa-runtime64.so.1
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Ошибка 2

```

**Comment by tpkessler** [comment] 2022-10-19 09:59
Duplicate of #870. Please see the readme or https://github.com/rocm-arch/rocm-arch/discussions/887 for several possible ways to solve your issue.

**Closed by tpkessler** 2022-10-19 09:59 UTC
