### ISSUE TITLE
hsa api failure

### ISSUE THREAD

**Issue by ReaperX01** [rocm-arch/rocm-arch#901] opened 2022-10-27 05:55 UTC
Hello, i have aproblem, when i enter **/opt/rocm/bin/rocminfo** on my terminal, it shows :

[reapertwo@arch ~]$ /opt/rocm/bin/rocminfo
ROCk module is loaded
hsa api call failure at: /build/rocminfo/src/rocminfo-rocm-5.3.0/rocminfo.cc:1148
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

I hope anyone can give the solution
My Laptop Specifications :
AMD FX-9830P
AMD Radeon RX560

**Comment by tpkessler** [comment] 2022-10-27 16:43
Duplicate of #870

**Closed by tpkessler** 2022-10-27 16:43 UTC

**Comment by tpkessler** [comment] 2022-10-27 16:47
Hey @ReaperX01! Your GPU is not supported by ROCm, see the [official list](https://community.amd.com/t5/knowledge-base/amd-rocm-hardware-and-software-support-document/ta-p/489937). That's why it's not working on your laptop.
