### ISSUE TITLE
[hsakmt-roct] out of date

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#32] opened 2020-03-08 22:49 UTC

**Comment by ranisalt** [comment] 2020-03-27 03:13
Looking at the PKGBUILD it seems this package is a duplicate of `roct-thunk-interface`. They download the same source and install the same thing, but hsakmt-roct also adds some links to /usr (which are unneeded)

**Comment by acxz** [comment] 2020-03-27 03:19
Yep, you're right. So then which one should we keep? `roct-thunk-interface` or `hsakmt-roct`?
I think we should stick as close to upstream as possible so that users have an easy time using ROCm's upstream documentation. ROCm uses `hsakmt-roct` as their package name for this repo and I suggest we do the same: https://github.com/RadeonOpenCompute/ROCm#rocm-binary-package-structure.

**Comment by ranisalt** [comment] 2020-03-27 03:25
`hsakmt-roct` is *very* outdated at this point, it should be probably better to move the PKGBUILD there, and rename the package. Problem though is how to tell AUR to redirect users to the new package.

**Comment by acxz** [comment] 2020-03-27 03:42
we can use the `replace` field.

**Comment by ranisalt** [comment] 2020-03-27 03:43
Does it work with AUR packages? TIL

**Comment by acxz** [comment] 2020-03-27 03:44
https://wiki.archlinux.org/index.php/PKGBUILD#replaces

**Comment by acxz** [comment] 2020-03-27 03:46
Also this is offtopic, but @ranisalt , you have some experience with building in chroots right? Do you think you can tackle the chroot issue? Those failures are the exact failures that are holding up getting the binary packages out on arch4edu.

**Comment by acxz** [comment] 2020-03-27 03:46
I can take care of this issue pretty easily.

**Comment by acxz** [comment] 2020-03-27 05:41
Keeping open until synced to AUR.
@neeshy

**Closed** 2020-03-27 06:34 UTC
Labels: out of date, sync to AUR
