### ISSUE TITLE
hsa-rocr build failure: unable to execute command: executable "ld.lld" doesn't exist

### ISSUE THREAD

**Issue by AdamNiederer** [rocm-arch/rocm-arch#882] opened 2022-10-14 21:47 UTC
`lld` should probably be a makedepend

```
[  1%] BUILDING bitcode for kCodeTrapHandlerV2_9...
[  1%] BUILDING bitcode for ocl_blit_object_gfx700...
[  2%] BUILDING bitcode for ocl_blit_object_gfx701...
[  4%] BUILDING bitcode for ocl_blit_object_gfx802...
[  5%] BUILDING bitcode for ocl_blit_object_gfx801...
[  9%] BUILDING bitcode for ocl_blit_object_gfx810...
[  9%] BUILDING bitcode for ocl_blit_object_gfx803...
[  9%] BUILDING bitcode for ocl_blit_object_gfx805...
[  9%] BUILDING bitcode for ocl_blit_object_gfx900...
[  9%] BUILDING bitcode for ocl_blit_object_gfx902...
[ 10%] BUILDING bitcode for kCodeTrapHandlerV2_1010...
[ 11%] BUILDING bitcode for ocl_blit_object_gfx702...
[ 12%] BUILDING bitcode for kCodeTrapHandlerV2_10...
[ 13%] BUILDING bitcode for kCodeTrapHandlerV2_11...
[ 13%] Built target link_libhsa-runtime64.so.1
[ 13%] Built target link_libhsa-runtime64.so
[ 15%] BUILDING bitcode for ocl_blit_object_gfx904...
[ 15%] BUILDING bitcode for ocl_blit_object_gfx906...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 16%] BUILDING bitcode for ocl_blit_object_gfx908...
clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
clang-14clang-14: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-14: error: ld.lld command failed with exit code 1 (use -v to see invocation)
```

**Comment by tpkessler** [comment] 2022-10-15 13:00
You have to build the package in a clean chroot, see the readme for details. Duplicate of #870

**Closed by tpkessler** 2022-10-15 13:00 UTC
