### ISSUE TITLE
[rocsolver] Package fails to build

### ISSUE THREAD

**Issue by R-Rudolph** [rocm-arch/rocm-arch#445] opened 2020-09-29 13:22 UTC
Hello, this is my first issue, I apologize in advance if I leave out any important information.

The rocsolver package fails to build with the following error:

```
[ 56%] Building CXX object rocsolver/library/src/CMakeFiles/rocsolver.dir/lapack/roclapack_getri_outofplace_batched.cpp.o
clang-11: warning: -lclang_rt.builtins-x86_64: 'linker' input unused [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-L/opt/rocm/llvm/lib/clang/11.0.0/include/../lib/linux' [-Wunused-command-line-argument]
fatal error: error in backend: Cannot select: 0x5626b52063c8: i64 = FrameIndex<0>
In function: _Z11bdsqrKernelI19rocblas_complex_numIdEdPS1_EviiiiPT0_lS4_lT1_iilS5_iilS5_iilPiiS3_S3_S3_S3_S4_l
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/rocm-arch/rocm-arch.git f3134e92e4ae99baa39151e725bd5dfbd9951ae3)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: warning: -lclang_rt.builtins-x86_64: 'linker' input unused [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-L/opt/rocm/llvm/lib/clang/11.0.0/include/../lib/linux' [-Wunused-command-line-argument]
clang-11: warning: -lclang_rt.builtins-x86_64: 'linker' input unused [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-L/opt/rocm/llvm/lib/clang/11.0.0/include/../lib/linux' [-Wunused-command-line-argument]
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:342: rocsolver/library/src/CMakeFiles/rocsolver.dir/auxiliary/rocauxiliary_bdsqr.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
fatal error: error in backend: Cannot select: 0x55ce61b88908: i64 = FrameIndex<0>
In function: _Z12getri_kernelI19rocblas_complex_numIdEPKPS1_S2_EviT0_iilPiilS6_T1_
fatal error: error in backend: Cannot select: 0x55f8c8587248: i64 = FrameIndex<0>
In function: _Z12getri_kernelI19rocblas_complex_numIdEPS1_S2_EviT0_iilPiilS4_T1_
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/rocm-arch/rocm-arch.git f3134e92e4ae99baa39151e725bd5dfbd9951ae3)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/rocm-arch/rocm-arch.git f3134e92e4ae99baa39151e725bd5dfbd9951ae3)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
fatal error: error in backend: Cannot select: 0x563e92702818: i64 = FrameIndex<0>
In function: _Z12getri_kernelI19rocblas_complex_numIdEPS1_S2_EviT0_iilPiilS4_T1_
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/rocm-arch/rocm-arch.git f3134e92e4ae99baa39151e725bd5dfbd9951ae3)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:485: rocsolver/library/src/CMakeFiles/rocsolver.dir/lapack/roclapack_getri_batched.cpp.o] Error 70
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:472: rocsolver/library/src/CMakeFiles/rocsolver.dir/lapack/roclapack_getri.cpp.o] Error 70
fatal error: error in backend: Cannot select: 0x5652e4dcead8: i64 = FrameIndex<0>
In function: _Z12getri_kernelI19rocblas_complex_numIdEPKPS1_S2_EviT0_iilPiilS6_T1_
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/rocm-arch/rocm-arch.git f3134e92e4ae99baa39151e725bd5dfbd9951ae3)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:498: rocsolver/library/src/CMakeFiles/rocsolver.dir/lapack/roclapack_getri_strided_batched.cpp.o] Error 70
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:511: rocsolver/library/src/CMakeFiles/rocsolver.dir/lapack/roclapack_getri_outofplace_batched.cpp.o] Error 70
```

The dependencies were installed via AUR.

System information:
Distribution: Manjaro
Kernel version: 5.8.6-1-MANJARO
GPU: Radeon VII (gfx906)

**Comment by acxz** [comment] 2020-09-29 13:29
Do note that we do not officially support Manjaro. Basically if we can't reproduce your issue then we can't fix it. We instead recommend Arch repo compatible distributions, such as EndeavourOS if you are looking for a GUI based install. Note with EndeavourOS you would be able to use arch4edu which is a binary repo, so you don't have to compile any of these packages.

**Comment by acxz** [comment] 2020-09-29 13:30
Closing as dup of #421

**Closed by acxz** 2020-09-29 13:30 UTC
