### ISSUE TITLE
[rocm-dkms] Missing kernel headers warning when after installing rocm-dkms

### ISSUE THREAD

**Issue by Awlexus** [rocm-arch/rocm-arch#296] opened 2020-07-11 19:37 UTC
As written in https://github.com/rocm-arch/tensorflow-rocm/issues/3, I'm getting the following warning after installing  `rocm-dkms`. 
```Unable to install module amdgpu-3.5/32 for kernel *: Missing kernel headers.```

Mirror used for downloading: `arch4edu` (https://mirrors.aliyun.com/arch4edu/$arch)

**Comment by acxz** [comment] 2020-07-12 13:43
hmm I can't seem to reproduce, can anyone else take a look at this? It might be a similar problem to #269

**Comment by Awlexus** [comment] 2020-07-12 18:07
I got this [reply](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1040#issuecomment-657248844) for my issue in tensorflow-upstread. Could this be the reason why?

**Comment by acxz** [comment] 2020-07-12 19:38
hmm could be although I have a feeling for this issue it doesn't matter. For the tensorflow-rocm issue that is most likely the case.

**Comment by acxz** [comment] 2020-07-15 22:35
@Awlexus I'm going to close this issue since I believe the issue is mostly likely the same or very closely related to #267

**Closed by acxz** 2020-07-15 22:35 UTC

**Comment by UKDOP** [comment] 2021-02-22 03:04
I met this issue before many times,  not only while install  rocm-dkms and found by googling, it may  be solved like this

sudo mv /var/lib/dpkg/info /var/lib/dpkg/info-old
sudo mkdir /var/lib/dpkg/info
sudo apt-get update

# sudo apt-get auto clean  # this step may be omitted in installing rocm-dskm it will deleting many packages 

sudo dpkg  --configure  -a

I have tried the above when installing rocm-dpkg in Debian 11,  custom 5.7 kernel
rock-dkms and rocm-dkms both will be set.

BUT when doing dpkg -i something again there will be lots of warnings !

So you should have a backup for your system if want to try the above.

Also would be grateful if anyone can help to solve the massive warnings shown on the screen after installing rocm-dkms.

**Comment by UKDOP** [comment] 2021-02-23 00:47
warning issue solved
Just need to copy all the files in /var/lib/dpkg/info-old to the empty /var/lib/dpkg/info again.

**Comment by UKDOP** [comment] 2021-02-23 01:03
Sorry for  mixing up 

The below thread is for failing to configure while install a package.

I met this issue  many times before, not only while install rocm-dkms and by googling,  it may be solved like below.

sudo mv /var/lib/dpkg/info /var/lib/dpkg/info-old
sudo mkdir /var/lib/dpkg/info
sudo apt-get update
sudo dpkg --configure -a

I have tried the above steps when installing rocm-dpkg in Debian 11, custom 5.7 kernel
rock-dkms and rocm-dkms both can be set.

then  need to copy all the files in /var/lib/dpkg/info-old to the empty /var/lib/dpkg/info 
No more warnings when to do  dpkg -i xxxxxx.deb next time.
