### ISSUE TITLE
[rocm-opencl-runtime] clinfo crashes without useful information

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#128] opened 2020-04-26 21:56 UTC
After the latest update of this package, when I try to clinfo, I get this:

```
[koz@Sebastian ~]$ clinfo
munmap_chunk(): invalid pointer
Aborted
```

**Comment by kozross** [comment] 2020-04-27 22:44
``rocminfo`` works correctly, though.

**Comment by kozross** [comment] 2020-04-27 22:50
It's actually even _weirder_ than that - this is a Heisenbug. Some executions of `clinfo` trigger this, and some don't.

**Comment by acxz** [comment] 2020-04-28 19:03
This should be resolved once the packages in #124 gets synced.

**Comment by kozross** [comment] 2020-04-28 22:22
@acxz Cool - will try again once that happens.

**Comment by acxz** [comment] 2020-05-01 03:45
@kozross some updates are out, this `clinfo` should work fine now, can you confirm and if so close this issue?

**Comment by kozross** [comment] 2020-05-01 05:38
``clinfo`` still has the same issue:

```
[koz@Sebastian ~]$ clinfo
munmap_chunk(): invalid pointer
Aborted
```

Weirder _still_ is this:

```
looking for conflicting packages...

Packages (1) llvm-amdgpu-3.3.0-2

Total Installed Size:  1506.31 MiB
Net Upgrade Size:      1007.99 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                   [########################################################] 100%
(1/1) checking package integrity                                                                 [########################################################] 100%
(1/1) loading package files                                                                      [########################################################] 100%
(1/1) checking for file conflicts                                                                [########################################################] 100%
(1/1) checking available disk space                                                              [########################################################] 100%
:: Processing package changes...
(1/1) upgrading llvm-amdgpu                                                                      [########################################################] 100%
==> Packages no longer required by any installed package:
    llvm-amdgpu
```

**Comment by acxz** [comment] 2020-05-03 20:51
hmmm, I am not able to reproduce this issue.

**Comment by kozross** [comment] 2020-05-03 20:54
Would I be able to provide anything to you that might help diagnose what this is doing? I'd love to help, but I have no clue where to even begin. I suspect there's a broken upgrade somewhere, so I might just rebuild the entire ROCm stack on my machine and see if it goes away.

**Comment by acxz** [comment] 2020-05-03 21:05
Yeah try a rebuild of the stack, if you are not familiar with it make sure to checkout the [`arch4edu`](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#arch4edu) repository they are hosting binary packages of the rocm stack. (Currently working on getting all of them on there, but the big ones are there already like hcc and llvm-amdgpu.

**Comment by kozross** [comment] 2020-05-03 22:31
That solved it! The only thing that weirds me out a bit is this, after a clean rebuild of ``rocm-opencl-runtime``:

```
==> Packages no longer required by any installed package:
       llvm-amdgpu llvm-roc rocm-cmake rocm-device-libs
```

**Comment by acxz** [comment] 2020-05-03 23:34
I believe since those are make dependencies they are not needed for the packages after you install them. I’ll go ahead and close this issue.

**Closed** 2020-05-03 23:51 UTC
Labels: runtime error

**Comment by emekoi** [comment] 2020-10-05 02:56
@kozross did you solve your problem by rebuilding the whole stack locally on your computer or did the `arch4edu`binary packages work? i am having a similar problem in which many of my `arch4edu` libs (`libamdhip64.so`, `libamdocl64.so`)cause segfaults whenever they are used, and i was wondering how you managed to solve your issue.

**Comment by acxz** [comment] 2020-10-05 03:03
It seemed that Kozross's issue was solved with using the arch4edu binaries. However, there have been two more rocm releases since then and there could be other issues. I recommend making another issue instead of commenting on a stale issue.

**Comment by emekoi** [comment] 2020-10-05 03:04
would it be better to open that issue here or in the arch4edu repo

**Comment by acxz** [comment] 2020-10-05 03:09
Technically since it is the arch4edu package that is giving you trouble you should post it there, but the problem is probably in this repo so that issue would be linked to a corresponding issue that you would have to create here. I would just post an issue here and we can take it from there.

**Comment by kozross** [comment] 2020-10-05 03:56
I am not using arch4edu packages - everything I use is built from the AUR.
