### ISSUE TITLE
[rocr-runtime] build failure

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [rocm-arch/rocm-arch#40] opened 2020-03-11 10:41 UTC
Hi guys, I'm facing build failure, here's the log 
[rocr-runtime.log](https://github.com/rocm-arch/rocm-arch/files/4317597/rocr-runtime.log)

However I think that the problem is the same described in this issue https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/47, indeed I tried building as they suggested

>TEMP_INCLUDE_DIR=\`mktemp -d\`
cp -LR /opt/rocm/include/* ${TEMP_INCLUDE_DIR}
rm -f ${TEMP_INCLUDE_DIR}/hsa.h
rm -f ${TEMP_INCLUDE_DIR}/amd_hsa_*.h 
mkdir build
cd build
cmake -DHSAKMT_INC_PATH:STRING=${TEMP_INCLUDE_DIR} \\
            -DHSAKMT_LIB_PATH:STRING=/opt/rocm/lib \\
            .. 
make

and it worked.
The problem seems to be that hsa headers in /opt/rocm/include are obsolete, whereas the updated one can be found in /opt/rocm/hsa/include.

(EDIT)

I implemented the workaround above in the `PKGBUILD` and now building with `makepkg` works fine.

**Comment by acxz** [comment] 2020-03-12 16:14
hmmm, I am not able to reproduce this issue. running `makepkg` with the existing PKGBUILD and using `yay` work for me with no hiccup. Just to make sure did you run with a clean build? Maybe try running it in a chroot as well.

**Comment by acxz** [comment] 2020-03-12 21:05
I have installed both `rocr-runtime` and `rocm-device-libs` but I still cannot reproduce this error.

**Comment by BrunoLiegiBastonLiegi** [comment] 2020-03-13 09:16
Actually you are right I tried to build it in a chroot enviroment and building went just fine. However in my system the problem is still there, I don't know...

**Comment by acxz** [comment] 2020-03-13 13:00
Maybe just nuke your `/opt/rocm/` folder and try again? I'll close this issue since it works for me and and in a chroot. Feel free to comment on here if you are still having trouble, though.

**Closed by acxz** 2020-03-13 13:00 UTC
