### ISSUE TITLE
[rocm-device-libs] use of unknown builtin

### ISSUE THREAD

**Issue by MaximMaximS** [rocm-arch/rocm-arch#869] opened 2022-10-09 11:45 UTC
Hello, when i try to build the latest update, it fails with

```
/home/maxim/.cache/yay/rocm-device-libs/src/ROCm-Device-Libs-rocm-5.3.0/ockl/src/dots.cl:45:32: error: use of unknown builtin '__builtin_amdgcn_sudot4' [-Wimplicit-function-declaration]
  if (!as && !bs && !s) return __builtin_amdgcn_sudot4(false, a, false, b, c, false);
                               ^
/home/maxim/.cache/yay/rocm-device-libs/src/ROCm-Device-Libs-rocm-5.3.0/ockl/src/dots.cl:57:32: error: use of unknown builtin '__builtin_amdgcn_sudot8' [-Wimplicit-function-declaration]
  if (!as && !bs && !s) return __builtin_amdgcn_sudot8(false, a, false, b, c, false);
                               ^
2 errors generated.
make[2]: *** [ockl/CMakeFiles/ockl.dir/build.make:155: ockl/dots.bc] Error 1
make[1]: *** [CMakeFiles/Makefile2:1878: ockl/CMakeFiles/ockl.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: rocm-device-libs
 ```

**Comment by tpkessler** [comment] 2022-10-09 13:05
Which version of `rocm-llvm` are you using?

**Comment by MaximMaximS** [comment] 2022-10-09 19:36
I updated rom-llvm manually, now #873 is happening.

**Comment by tpkessler** [comment] 2022-10-10 10:04
Duplicate of #870

**Closed by tpkessler** 2022-10-10 10:04 UTC
Labels: build error
