### ISSUE TITLE
hsa-rocr build error

### ISSUE THREAD

**Issue by throwm8** [rocm-arch/rocm-arch#874] opened 2022-10-10 14:47 UTC
Trying to build hsa-rocr 5.3.0 fails with invalid target id errors, here's the build log

```
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Found LibElf: /usr/lib/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Checking for module 'libdrm'
--   Found libdrm, version 2.4.113
-- Looking for __NR_memfd_create
-- Looking for __NR_memfd_create - found
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/libtinfo.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.12") 
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.10.2") 
Using CPACK_DEBIAN_PACKAGE_RELEASE local
RESULT_VARIABLE No such file or directory OUTPUT_VARIABLE: 
CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/.cache/yay/hsa-rocr/src/build
[  0%] BUILDING bitcode for ocl_blit_object_gfx700...
[  1%] BUILDING bitcode for ocl_blit_object_gfx803...
[  2%] BUILDING bitcode for ocl_blit_object_gfx802...
[  3%] BUILDING bitcode for ocl_blit_object_gfx810...
[  4%] BUILDING bitcode for ocl_blit_object_gfx805...
[  5%] BUILDING bitcode for ocl_blit_object_gfx702...
[  6%] BUILDING bitcode for ocl_blit_object_gfx801...
[  9%] BUILDING bitcode for ocl_blit_object_gfx900...
[  9%] BUILDING bitcode for kCodeTrapHandlerV2_11...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx909...
[ 10%] BUILDING bitcode for ocl_blit_object_gfx904...
[ 11%] BUILDING bitcode for kCodeTrapHandlerV2_9...
[ 13%] BUILDING bitcode for ocl_blit_object_gfx906...
[ 13%] BUILDING bitcode for ocl_blit_object_gfx902...
[ 14%] BUILDING bitcode for kCodeTrapHandlerV2_10...
[ 17%] BUILDING bitcode for ocl_blit_object_gfx1010...
[ 17%] BUILDING bitcode for ocl_blit_object_gfx1011...
[ 17%] BUILDING bitcode for ocl_blit_object_gfx701...
[ 18%] BUILDING bitcode for ocl_blit_object_gfx90a...
[ 19%] BUILDING bitcode for kCodeTrapHandlerV2_1010...
[ 21%] BUILDING bitcode for ocl_blit_object_gfx90c...
[ 21%] BUILDING bitcode for ocl_blit_object_gfx908...
[ 21%] Built target link_libhsa-runtime64.so
[ 21%] Built target link_libhsa-runtime64.so.1
[ 22%] BUILDING bitcode for ocl_blit_object_gfx1013...
[ 23%] BUILDING bitcode for ocl_blit_object_gfx1012...
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/build.make:112: core/runtime/trap_handler/kCodeTrapHandlerV2_11.hsaco] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 24%] BUILDING bitcode for ocl_blit_object_gfx1030...
make[1]: *** [CMakeFiles/Makefile2:309: core/runtime/trap_handler/CMakeFiles/amd_trap_handler_v2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] BUILDING bitcode for ocl_blit_object_gfx1031...
[ 26%] BUILDING bitcode for ocl_blit_object_gfx1032...
[ 27%] BUILDING bitcode for ocl_blit_object_gfx1033...
[ 28%] BUILDING bitcode for ocl_blit_object_gfx1034...
[ 30%] BUILDING bitcode for ocl_blit_object_gfx1035...
[ 31%] BUILDING bitcode for ocl_blit_object_gfx1102...
[ 32%] BUILDING bitcode for ocl_blit_object_gfx1103...
[ 32%] BUILDING bitcode for ocl_blit_object_gfx1100...
[ 33%] BUILDING bitcode for ocl_blit_object_gfx1036...
clang-14: error: invalid target ID 'gfx1102'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1103'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1100'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
clang-14: error: invalid target ID 'gfx1036'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:168: image/blit_src/ocl_blit_object_gfx1102] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:163: image/blit_src/ocl_blit_object_gfx1100] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:173: image/blit_src/ocl_blit_object_gfx1103] Error 1
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:158: image/blit_src/ocl_blit_object_gfx1036] Error 1
make[1]: *** [CMakeFiles/Makefile2:335: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hsa-rocr
```

**Comment by tpkessler** [comment] 2022-10-10 14:49
Duplicate of #870. Please try to build the package in a clean chroot. The readme has more details on this.

**Closed by tpkessler** 2022-10-10 14:49 UTC
