### ISSUE TITLE
comgr 5.3.0-1 build fails with SymbolizableObjectFile.h: No such file or directory

### ISSUE THREAD

**Issue by SpotlightKid** [rocm-arch/rocm-arch#872] opened 2022-10-09 18:31 UTC
```
/home/chris/.cache/pikaur/build/comgr/src/ROCm-CompilerSupport-rocm-5.3.0/lib/comgr/src/comgr-symbolizer.cpp:40:10: fatal error: llvm/DebugInfo/Symbolize/SymbolizableObjectFile.h: No such file or directory
   40 | #include "llvm/DebugInfo/Symbolize/SymbolizableObjectFile.h"
```

Relevant build output: https://cpaste.org/?a066c4943b581ec0#G6ubrncNuUfg3trnL1vsTBSA3oFFWwsHT7aCqtraZa6y

Installed llvm (and latest in extra) is 14.0.6-3

**Comment by tpkessler** [comment] 2022-10-10 09:57
Duplicate of #870

**Closed by tpkessler** 2022-10-10 09:57 UTC
