### ISSUE TITLE
[llvm-amdgpu] Run out of memory when compiling

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#197] opened 2020-06-05 23:45 UTC
Whenever I try to compile this package, I get an out of memory, similar to this:

```
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
make[2]: *** [tools/clang/tools/clang-shlib/CMakeFiles/clang-cpp.dir/build.make:2016: lib/libclang-cpp.so.11git] Error 1
make[2]: *** Deleting file 'lib/libclang-cpp.so.11git'
make[1]: *** [CMakeFiles/Makefile2:28449: tools/clang/tools/clang-shlib/CMakeFiles/clang-cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Turning parallelism off in my `makepkg.conf` doesn't fix this. I have 32GB of RAM available on my machine, and have not encountered this problem before.

**Comment by acxz** [comment] 2020-06-05 23:54
Can you give us the complete build log and post it on a gist?

**Comment by kozross** [comment] 2020-06-06 03:10
[Here's a log](https://github.com/rocm-arch/rocm-arch/files/4739288/llvm-amdgpu-3.5.0-1-x86_64-build.log.zip). This was made by ``makepkg -srL``.

**Comment by acxz** [comment] 2020-06-06 03:50
Thx for the log but can U unzip or post the contents directly. Kinda inconvenient to view as a zip file

**Comment by noradtux** [comment] 2020-06-06 06:45
I am experiencing the same issue, also 32GiB of RAM.
Console output, building through pikaur:
https://gist.github.com/noradtux/56fef275a3777f02d12c003c1eac3694

**Comment by NorthSailor** [comment] 2020-06-06 09:41
Same, even though with just 16 GiB of RAM, however it also fills the entire 16 GiB swap partition.
Single-threaded compilation doesn't seem to make a difference.

**Comment by agravgaard** [comment] 2020-06-06 11:30
I was getting the same issue, after the first run I just changes the `-j$THREADS` in the makeflags to a more appropriate number, which worked well for me.
The linking starting at around 85% completion required about 4-5 GB of ram per thread.
I have an 8 thread CPU and only 24 GB of RAM and about 9 GB in swap.

**Comment by pepper-jk** [comment] 2020-06-06 12:54
> The linking starting at around 85% completion required about 4-5 GB of ram per thread.

Thanks for the info. Ran into the same issue this morning. 32GB RAM and 12 thread CPU. Tried with 12 (all), 10 and 6 threads already. Always froze/locked around 98%, even with nothing else open. I will now run it on 3 threads and hope it does not need more than 15 GB, so that I can work normally during the compilation.

I really appreciate the multi threaded compiling, since most AUR packages just build super slow with the 1 thread only default. But one has to keep in mind the RAM usage. Using all cores might not be the best default here.

**Comment by pepper-jk** [comment] 2020-06-06 14:25
Another Warning:
`llvm-amdgpu` needs >50GB free disk space during build

It just crashed on me at 98%. -.-

_Originally posted by @pepper-jk in https://github.com/rocm-arch/rocm-arch/issues/204#issuecomment-640067921_

**Comment by kozross** [comment] 2020-06-06 18:22
@agravgaard How do you disable parallelism? I tried removing ``-j11`` from my ``MAKEFLAGS`` in makepkg.conf``, but that did nothing for me.

@acxz Sorry, [is this better](https://gist.github.com/kozross/a13d7824c212225e7170ec4256781ce5)?

**Comment by noradtux** [comment] 2020-06-06 18:35
@kozross You need to edit the PKGBUILD, it has its own config for parallelism.
Disabling parallelism made the build work for me.

**Comment by kozross** [comment] 2020-06-06 18:40
@noradtux This is a bad configuration then IMHO. This isn't something that a PKGBUILD should decide for the user - deferring to our own MAKEFLAGS is the proper behaviour.

**Comment by acxz** [comment] 2020-06-06 20:32
@kozross I sort of agree with you. This actually came up a long time back See: the issue #43 which this is a duplicate of and the attempted PR #58

In lieu of this we can and should revisit this issue.
Pinging @rigred since he was involved in closing the issue/PR and @ranisalt since he participated in the discussions as well.

**Comment by pepper-jk** [comment] 2020-06-06 20:38
A small update regarding the disk space.

My room mate tried to build it on his machine and 120GB of free disk space was not enogh.

He was able to build and check, but during installation his disk space ran out.

Is this considered normal? o.O

**Comment by noradtux** [comment] 2020-06-06 20:41
I noticed, this llvm is being build using make while Arch's llvm-package is using ninja to build it. Maybe make isn't fully supported anymore?

**Comment by t1nux** [comment] 2020-06-06 20:48
I can' believe it's disk space that running out. I have 693 GB free and it's failing at 98%: https://pastebin.com/NfYjpPi3

**Comment by pepper-jk** [comment] 2020-06-06 22:32
> I can't believe it's disk space that's running out. I have 693 GB free and it's failing at 98%: https://pastebin.com/NfYjpPi3

Well I did not say that memory isn't a problem.
But once you reduce the number of jobs/threads make uses so that memory isn't an issue anymore, disk space becomes an issue.

**Comment by ranisalt** [comment] 2020-06-06 22:38
What flags are you using for `CFLAGS`, `CXXFLAGS` and `LDFLAGS`? LTO is usually the culprit as it requires ludicrous amounts of RAM and stores huge object files.

>  `llvm-amdgpu` needs >50GB free disk space during build

I build it inside `/tmp` which is limited to 8GB and it never runs out of space, by a fair margin. It seems like you have a leak due to flags.

> I really appreciate the multi threaded compiling, since most AUR packages just build super slow with the 1 thread only default

Seriously consider using `ccache`. Even if it fails, you will jump th the same 98% quickly next time.

> I noticed, this llvm is being build using make while Arch's llvm-package is using ninja to build it. Maybe make isn't fully supported anymore?

Not the case. We use `make` because it is part of `base-devel`, so we avoid adding another dependency. `ninja` uses 1 job per CPU thread by default so it would happen too, and out of our control.

**Comment by pepper-jk** [comment] 2020-06-06 22:44
> What flags are you using for `CFLAGS`, `CXXFLAGS` and `LDFLAGS`? LTO is usually the culprit as it requires ludicrous amounts of RAM and stores huge object files.
> 
> > `llvm-amdgpu` needs >50GB free disk space during build
> 
> I build it inside `/tmp` which is limited to 8GB and it never runs out of space, by a fair margin. It seems like you have a leak due to flags.

I use the most current PKGBUILD from the AUR, so if there is any leakage it is due to the PKGBUILD, is it not? Besides `-j3` I did not change anything in the PKGBUILD.

**Comment by ranisalt** [comment] 2020-06-06 22:45
I mean your flags in `makepkg.conf`

**Comment by pepper-jk** [comment] 2020-06-06 22:49
Here you go:

```
#-- Compiler and Linker Flags
# -march (or -mcpu) builds exclusively for an architecture
# -mtune optimizes for an architecture, but builds for whole processor family
CPPFLAGS="-D_FORTIFY_SOURCE=2"
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong"
CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro"
```

**Comment by pepper-jk** [comment] 2020-06-06 22:59
> `ninja` uses 1 job per CPU thread by default so it would happen too, and out of our control.

Yes it does, but it is not out of your control, you can still specify the number of jobs, just like with make.

> so we avoid adding another dependency.

But I get the dependency reason.

**Comment by ranisalt** [comment] 2020-06-06 23:02
Hm, you are using pretty standard flags. My intuition is upstream has enforced a flag inside their CMake files and that's causing high memory usage. I will investigate it.

**Comment by kozross** [comment] 2020-06-07 23:30
Having attempted forcing ``THREADS`` to ``1``, I can confirm that this package will build. However, it does eat a huge amount of disk space (2GB+ for the final package, and probably a lot more as source). I'm unsure why this is happening, since older versions were nothing like this large).

**Comment by helloworld1** [comment] 2020-06-08 03:51
I setup a cgroup to make only 4 CPUs available to the package and be able to build within 32G of ram. But it also eats 69.5G space in source

**Comment by DerVerruckteFuchs** [comment] 2020-06-08 05:05
I tried installing the update from the AUR, and was pretty shocked at the disk usage. I got to no space left and then the compile failed. After completely clearing out my ccache and the llvm-amdgpu package directory with source, I'm back to 127 GB of free space. While we're all comparing, this is on a system with 8 threads and 16 GB RAM/32 GB swap. At some points all of my RAM and swap were getting used up. Normally I can have web browsing somewhat to mostly unimpeded during a build, but things got brought down to a crawl and I think either Firefox crashed or got OOM killed.

From [this comment thread on Hacker News](https://news.ycombinator.com/item?id=23139396), it looks like an issue with using debug builds and/or static linking instead of dynamic linking. I looked over the current PKGBUILD on the AUR and `-DCMAKE_BUILD_TYPE=Release` is absent. So I think it's making a massing 70 GB+ debug build. As for the linking, I don't see `LLVM_LINK_LLVM_DYLIB` or `LLVM_BUILD_LLVM_DYLIB` either, so we may be seeing an even more massive static build as well.  

Another thing I noticed is that [upstream deprecated HCC in favor of HIP-Clang.](https://github.com/RadeonOpenCompute/ROCm#heterogeneous-compute-interface-for-portability) As far as I remember, llvm-amdgpu was a thing before the deprecation, so it may be more of about recent llvm 9 -> 10 changes.

I'm going to try adding those flags to the PKGBUILD and see if that helps any.

**Comment by kozross** [comment] 2020-06-08 05:54
``-DCMAKE_BUILD_TYPE=Release`` definitely ought to be there. I also think the logic setting ``THREADS`` should be removed - we can have it use our ``makepkg.conf`` settings instead.

**Comment by DerVerruckteFuchs** [comment] 2020-06-08 07:19
With the build type set to Release and both the aforementioned dynamic linking options set to `ON`, my compile just finished and everything seems to have installed correctly. I started with 127 GB and am at 123 GB after everything installed. With pacman the total install size is listed as 496.44 MiB. Also RAM/swap usage was much more reasonable. Compiling and watching youtube was at most 11 GB RAM used with little to no swap usage.

Yes, please don't set the threads used in the PKGBUILD. I normally use all of my available threads, so I didn't notice much beside seeing the thread logic in the PKGBUILD. I get a bit annoyed when other AUR package maintainers set compiles to a single thread for some reason. Especially if it's not justified in a comment. There was at least one instance where I had no idea why an AUR package was only compiling with a single thread, and things usually go wrong when I've mis-configured things. I ended up troubleshooting my configs and a number of other things. I couldn't figure out why my computer was disobeying me until I chased it down to the PKGBUILD. I imagine people who don't normally max out their threads in their `makepkg.conf` would be at least a bit bothered by it. Unless there is a special reason for explicitly setting it in the PKGBUILD (e.g. builds fail unless X threads are used), then there's no need to set it in the PKGBUILD.

Excluding my personal experience, the [second bullet point in the following portion of the Arch Wiki](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_etiquette) says not to use unnecessary variables or functions as they could conflict with what is in `makepkg.conf`. The thread logic directly makes changes to `MAKEFLAGS` and it's not necessary for the build to succeed AFAIK, so that is a no-go.

Just in case anyone has missed it, the [llvm documentation](https://releases.llvm.org/10.0.0/docs/CMake.html) shows that both dynamic linking options I listed are set to `OFF` by default. I've only been checking in on PKGBUILD stuff now and again, so I don't know if the builds being statically linked is a deliberate decision or not.

**Comment by kozross** [comment] 2020-06-08 08:19
Seems like a straightforward set of fixes. @acxz - could we get this?

**Comment by tpkessler** [comment] 2020-06-08 10:07
As @acxz  mentioned before, we had this discussion before:

> This actually came up a long time back See: the issue #43 which this is a duplicate of and the attempted PR #58

It would be no problem to set the build type to release and remove the calculation of NUM_THREADS. But we cannot turn on dynamic linking, see PR https://github.com/rocm-arch/rocm-arch/pull/131

**Comment by acxz** [comment] 2020-06-08 12:32
Setting the build type is a user configuration option see: https://wiki.archlinux.org/index.php/CMake_package_guidelines#CMake_can_automatically_override_the_default_compiler_optimization_flag

> It's very common to see people running CMake with the -DCMAKE_BUILD_TYPE=Release option. Some upstream projects even inadvertently include this option in their building instructions, but this produces an undesired behavior.

> Each build type causes CMake to automatically append a set of flags to CFLAGS and CXXFLAGS. When using the common Release build type, it automatically appends the -O3[1] compiler optimization flag, and this overrides the default Arch Linux flag which currently is -O2 (defined in the makepkg configuration file). This is undesired, as it deviates from the Arch Linux targeted optimization level. 

Note: removing the build type may cause other issues with the software (read more under the linked section). If you can give me proof (directly linked from the CMake code) that other flags need to be added we can add those flags back in.

Having said that the llvm package from Arch Repos does use `-DCMAKE_BUILD_TYPE=Release`. https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/llvm#n33
As such I would accept a PR with this change. However, this is an exception that has precedent and not a rule for CMake based projects.

As for `THREADS`
https://github.com/rocm-arch/rocm-arch/blob/eb413e0cc4a21b0b9232a727badf5abab325e83b/llvm-amdgpu/PKGBUILD#L17-L18

It seems that the 1.5G per unit calculation is now outdated and has most likely increased. Ideally `MAKEFLAGS` should not be in the PKGBUILD, however, that logic was first put in place as a *limiting* factor. If you had specified a large number of threads than your computer would OOM. I would like this logic to be rewritten such that if your specified THREADS don't cause OOM, keep the user's THREADS else (and only then) overwrite them to something that their system can handle. As it is now tho, I believe the best move forward is to remove this logic and use the user's THREADS for now, until such logic can be rewritten appropriately, respecting user choice and safeguarding the user as necessary.

> could we get this?

Send a PR my way and I'll review it ;)

**Comment by pepper-jk** [comment] 2020-06-09 16:34
Thanks for all your information.

As a **workaround** I was able to build and install `llvm-amdgpu` with the following PKGBUILD:

```
# Maintainer: acxz <akashpatel2008 at yahoo dot com>

pkgname=llvm-amdgpu
pkgdesc='Radeon Open Compute - LLVM toolchain (llvm, clang, lld)'
pkgver=3.5.0
pkgrel=1
arch=('x86_64')
url='https://github.com/RadeonOpenCompute/llvm-project'
license=('custom:Apache 2.0 with LLVM Exception')
depends=(z3)
makedepends=(cmake python)
source=("${pkgname}-${pkgver}.tar.gz::$url/archive/rocm-$pkgver.tar.gz")
sha256sums=('4878fa85473b24d88edcc89938441edc85d2e8a785e567b7bd7ce274ecc2fd9c')
_dirname="$(basename "$url")-$(basename "${source[0]}" .tar.gz)"

build() {
    # building LLVM/Clang requires ~1.5G per unit
    THREADS=$(( ($(getconf _PHYS_PAGES) * $(getconf PAGESIZE)) / 1610612736 ))
    if [ "$THREADS" -lt 1 ]; then
        THREADS=1
    fi
    NPROC=$(nproc)
    if [ "$THREADS" -gt $(nproc) ]; then
        THREADS="$NPROC"
    fi

    cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX='/opt/rocm/llvm' \
          -DLLVM_HOST_TRIPLE=$CHOST \
          -DLLVM_BUILD_UTILS=ON \
          -DLLVM_ENABLE_BINDINGS=OFF \
          -DLLVM_ENABLE_OCAMLDOC=OFF \
          -DLLVM_ENABLE_PROJECTS='llvm;clang;lld' \
          -DLLVM_TARGETS_TO_BUILD='AMDGPU;X86' \
          -DOCAMLFIND=NO \
          "$_dirname/llvm"
#    MAKEFLAGS="$MAKEFLAGS -j$THREADS" make
    ninja -j3
}

check() {
    ninja check
}

package() {
    DESTDIR="$pkgdir" ninja install
}
```

Please be aware that I used `ninja`.

**Comment by ranisalt** [comment] 2020-06-09 22:03
You would have the same output by running `make -j3`. You might solve the issue for your specific machine but you completely missed the point of the solution here.

I'm with @acxz on this.

**Comment by kozross** [comment] 2020-06-09 23:09
I also _strongly_ do not suggest the use of `ninja`. Gentoo have had issues of it blatantly ignoring user settings vis a vis parallelism (which I have experienced very personally). CMake can generate Unix makefiles, and since these would respect `MAKEFLAGS`, I suggest keeping to that.

**Comment by pepper-jk** [comment] 2020-06-10 07:43
> You would have the same output by running `make -j3`. You might solve the issue for your specific machine but you completely missed the point of the solution here.
> 
> I'm with @acxz on this.

If I was of the opinion that this **workaround** is the solution I would have issued a pull request.
As I didn't I'm not suggesting it as a solution
All I wanted to do is post the workaround I personally used in case someone wanted to compile `llvm-amdgpu` sooner rather than later, when this issue finally gets fixed properly.

**Comment by ranisalt** [comment] 2020-06-10 23:32
See, the way `ninja` works, it would build faster even with the same number of jobs that `make`. If it works for you, I would suggest even keeping it - though you will need to fix pkgbuild on every update.

**Comment by pepper-jk** [comment] 2020-06-11 09:43
> though you will need to fix pkgbuild on every update.

I am aware of that, that is why I'm assuming that this bug will be fixed before the next update.
If we need to manually fix every aur package from this repo to get ROCM to work, what is the point of having the aur packages?

**Comment by rigred** [comment] 2020-06-14 12:57
We need to please verify the build type of all packages!
This was being compiled a debug instead of release which has far reaching consequences for all packages that rely on this.
Especially build resources and runtime kernel performance.

**Comment by tpkessler** [comment] 2020-06-14 13:02
I've had this discussion several times before. The reason why we do not specify `CMAKE_BUILD_TYPE=Release` is [here](https://wiki.archlinux.org/index.php/CMake_package_guidelines#CMake_undesired_behaviors). Many ROCm libs (if not all) set their default build type to release.

**Comment by rigred** [comment] 2020-06-14 13:05
In this case that was not happening.
Thus we need to verify what's actually being built.

**Closed by rigred** 2020-06-14 13:05 UTC

**Comment by acxz** [comment] 2020-06-14 14:04
Agreed ideally we should be verifying the files being built/packaged ([reproducible](https://reproducible-builds.org/) builds anyone? As of now, we will take build types case by case and as we slowly round out the packages we have for rocm compare the output deb packages with ours.

**Comment by kode54** [comment] 2020-06-15 05:10
I just checked, rocm-opencl-runtime 3.5.0-1 also builds a debug build. I only noticed because Luxmark reported the device name as "OpenCL 2.0 AMD-APP.dbg".
