### ISSUE TITLE
rocm-cmake PKGBUILD cannot work in it's current state

### ISSUE THREAD

**Issue by rigred** [rocm-arch/rocm-arch#28] opened 2020-03-08 06:51 UTC
The current PKGBUILD of rocm-cmake tries to write to a root directory during the package phase.
This is forbidden by the PKGBUILD as it is not writing to the fakeroot $pkgdir directory.
```
==> Making package: rocm-cmake 3.0.0-1 (Sun Mar  8 08:47:30 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found roc-3.0.0.tar.gz
==> Validating source files with sha256sums...
    roc-3.0.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting roc-3.0.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rgr/code/PKGBUILDS/rocm-arch/rocm-cmake/src/build
==> Entering fakeroot environment...
==> Starting package()...
Install the project...
-- Install configuration: ""
-- Up-to-date: /opt/rocm/./share
-- Up-to-date: /opt/rocm/./share/rocm
-- Up-to-date: /opt/rocm/./share/rocm/cmake
-- Installing: /opt/rocm/./share/rocm/cmake/ROCMPackageConfigHelpers.cmake
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/rgr/code/PKGBUILDS/rocm-arch/rocm-cmake/src/rocm-cmake-roc-3.0.0/share/rocm/cmake/ROCMPackageConfigHelpers.cmake"
  to "/opt/rocm/./share/rocm/cmake/ROCMPackageConfigHelpers.cmake":
  Permission denied.


make: *** [Makefile:86: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```

Instead I suggest changing the PKGBUILD to this older (but correct) code

```
# Original build: fermyon <antifermion@protonmail.com>
# Maintainer: Markus Näther <naetherm@cs.uni-freiburg.de>
pkgname=rocm-cmake
pkgver=3.0.0
pkgrel=1
pkgdesc="cmake modules for common build tasks needed for the ROCM software stack"
arch=(x86_64)
url="https://github.com/RadeonOpenCompute/rocm-cmake"
license=(MIT)
makedepends=(git cmake)
conflicts=(rocm-cmake-git)
source=("https://github.com/RadeonOpenCompute/rocm-cmake/archive/roc-$pkgver.tar.gz")
sha256sums=('9393fd534a100e8da55f44d0625337d76f3c7890e0297fe690c9e7d384b205ef')

build() {
    cd "$srcdir/${pkgname}-roc-${pkgver}"
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX="$pkgdir/opt/rocm" ..
}

package() {
    cd "$srcdir/${pkgname}-roc-${pkgver}/build"
    cmake --build . --target install
}
```

Specifically note the line
```
    cmake -DCMAKE_INSTALL_PREFIX="$pkgdir/opt/rocm" ..
```
Which sets the $pkgdir value as makepkg will otherwise attempt to write to the root `/opt/rocm` path.

**Comment by acxz** [comment] 2020-03-08 14:52
Thanks for the report @rigred, I can also reproduce the error.
However, the older PKGBUILD may have been working, but it not correct either. The `pkgdir` variable should not be used in the `build()` function. See: https://www.archlinux.org/pacman/PKGBUILD.5.html

**Comment by neeshy** [comment] 2020-03-08 19:05
Seems like a simple make DESTDIR=$pkgdir install works equivalently.

**Comment by acxz** [comment] 2020-03-08 20:24
totally overlooked that, closing this issue then due to https://github.com/rocm-arch/rocm-arch/commit/f002f8967b524a9c2c3e0124de4df2eae87ed8e3. 

@rigred let us know if you still have any issues.

**Closed by acxz** 2020-03-08 20:24 UTC
