### ISSUE TITLE
[rocblas] Build picks up system clang and fails due to missing GPU support

### ISSUE THREAD

**Issue by oleid** [rocm-arch/rocm-arch#412] opened 2020-09-08 14:57 UTC
On my system, I have upstream `clang` installed. It would seem that gets picked up by `Tensile` in `rocblas` build.  Resulting in errors like:

```
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v62, vcc, v35, v36
^
/home/oleid/.cache/rua/build/rocblas/src/assembly/Cijk_Alik_Bljk_SB_MT64x128x16_SN_1LDSB0_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_DVO0_EPS16o9OVAdG3a8yaZiHPvF5bmUDfrQlQi3OgqWhejOFJI4=.s:3444:1: note: while in macro instantiation
_v_add_lshl_u32 v62, v35, v36, 0x2                 // emitLddChange: accumulate d0 lower and *= bpe into addr
^
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v36, vcc, v32, 33 
^
/home/oleid/.cache/rua/build/rocblas/src/assembly/Cijk_Alik_Bljk_SB_MT64x128x16_SN_1LDSB0_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_DVO0_EPS16o9OVAdG3a8yaZiHPvF5bmUDfrQlQi3OgqWhejOFJI4=.s:3447:1: note: while in macro instantiation
_v_add_co_u32 v36, vcc, v32, 33                    // coord0.1: coord0 += d0*sg0*VW + vc0
^
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v64, vcc, v34, v36
^
/home/oleid/.cache/rua/build/rocblas/src/assembly/Cijk_Alik_Bljk_SB_MT64x128x16_SN_1LDSB0_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_DVO0_EPS16o9OVAdG3a8yaZiHPvF5bmUDfrQlQi3OgqWhejOFJI4=.s:3451:1: note: while in macro instantiation
_v_add_lshl_u32 v64, v34, v36, 0x2                 // scaleToBpe: accumulate d0 lower and *= bpe into Cin addr
^
<instantiation>:1:1: error: instruction not supported on this GPU
v_add_u32 v64, vcc, v35, v36
^
/home/oleid/.cache/rua/build/rocblas/src/assembly/Cijk_Alik_Bljk_SB_MT64x128x16_SN_1LDSB0_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_DVO0_EPS16o9OVAdG3a8yaZiHPvF5bmUDfrQlQi3OgqWhejOFJI4=.s:3454:1: note: while in macro instantiation
_v_add_lshl_u32 v64, v35, v36, 0x2                 // emitLddChange: accumulate d0 lower and *= bpe into addr
^
warning: ISA: (9, 0, 6)  is not supported; overriding with  (9, 0, 0)
Command '['/usr/bin/clang++', '-x', 'assembler', '-target', 'amdgcn-amd-amdhsa', '-mcpu=gfx900', '-c', '-o', '/home/oleid/.cache/rua/build/rocblas/src/assembly/Cijk_Alik_Bljk_SB_MT64x128x16_SN_1LDSB0_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_DVO0_EPS16o9OVAdG3a8yaZiHPvF5bmUDfrQlQi3OgqWhejOFJI4=.o', '/home/oleid/.cache/rua/build/rocblas/src/assembly/Cijk_Alik_Bljk_SB_MT64x128x16_SN_1LDSB0_APM1_AF0EM1_AF1EM1_AMAS3_ASBE01_ASEM1_BL1_DTL0_DVO0_EPS16o9OVAdG3a8yaZiHPvF5bmUDfrQlQi3OgqWhejOFJI4=.s']' returned non-zero exit status 1.
```

Having had a look at tensile's `Common.py` the only work-around due to how the function `locateExe` is made is to 

```bash
export PATH=/opt/rocm/llvm/bin:$PATH
```
as that function searches `PATH` first before the default path is used.

I'm not sure what the cleanest work-around is. Possibly extending PATH in the PKGBUILD?

**Comment by acxz** [comment] 2020-09-08 15:31
Interesting find, I'm guess this is the cause for #410

**Comment by oleid** [comment] 2020-09-09 07:37
Thanks for adding a work-around. You want to keep this issue open until no work-around is needed, I presume?

**Comment by acxz** [comment] 2023-09-09 16:00
@tpkessler sorry for the ping, but do you mind looking at this issue and closing it considering rocblas is not part of this repo anymore?

**Closed** 2024-07-20 23:50 UTC
Labels: build error, patched
