### ISSUE TITLE
[rocsolver] failed to build rocsolver

### ISSUE THREAD

**Issue by IndML101** [rocm-arch/rocm-arch#444] opened 2020-09-29 11:39 UTC
Hi

I was trying to install rocm on Manjaro 20.1 linux kernel 5.8.6-1, I got the following error. any fix for that:

fatal error: error in backend: Cannot select: 0x55dc8cf97148: i64 = FrameIndex<0>
In function: _Z11bdsqrKernelI19rocblas_complex_numIdEdPS1_EviiiiPT0_lS4_lT1_iilS5_iilS5_iilPiiS3_S3_S3_S3_S4_l
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 38fffda570a017745da11c40ed8991c3c70a3281)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:342: rocsolver/library/src/CMakeFiles/rocsolver.dir/auxiliary/rocauxiliary_bdsqr.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/gubberex/.cache/yay/rocsolver/src/build'
make[1]: *** [CMakeFiles/Makefile2:131: rocsolver/library/src/CMakeFiles/rocsolver.dir/all] Error 2
make[1]: Leaving directory '/home/gubberex/.cache/yay/rocsolver/src/build'
make: *** [Makefile:171: all] Error 2
make: Leaving directory '/home/gubberex/.cache/yay/rocsolver/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
error making: rocsolver

**Comment by acxz** [comment] 2020-09-29 12:10
Do note that we do not officially support Manjaro. Basically if we can't reproduce your issue then we can't fix it. We  instead recommend Arch repo compatible distributions, such as [EndeavourOS](https://endeavouros.com/) if you are looking for a GUI based install. Note with EndeavourOS you would be able to use [arch4edu](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux) which is a binary repo, so you don't have to compile any of these packages.

**Comment by acxz** [comment] 2020-09-29 12:11
Closing as dup of #421

**Closed by acxz** 2020-09-29 12:11 UTC
